import 'package:clipboard_watcher/clipboard_watcher.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter/material.dart';
import 'package:injectable/injectable.dart';
import '../../features/clipboard/presentation/bloc/clipboard_bloc.dart';
import '../../features/clipboard/presentation/bloc/clipboard_event.dart';

@singleton
class ClipboardWatcherService with ClipboardListener {
  BuildContext? _context;
  String? _lastAppCopiedText;

  void initialize(BuildContext context) {
    _context = context;
    clipboardWatcher.addListener(this);
    clipboardWatcher.start();
  }

  void dispose() {
    clipboardWatcher.removeListener(this);
    clipboardWatcher.stop();
    _context = null;
  }

  /// Copies text to the system clipboard and marks it as an app-generated copy
  /// to prevent the watcher from adding it back as a new clip.
  Future<void> copyToClipboard(String text) async {
    _lastAppCopiedText = text;
    await Clipboard.setData(ClipboardData(text: text));
  }

  @override
  void onClipboardChanged() async {
    if (_context == null) return;

    final data = await Clipboard.getData(Clipboard.kTextPlain);
    final text = data?.text;

    if (text != null && text.isNotEmpty) {
      // Check if this clip was generated by the app itself
      if (text == _lastAppCopiedText) {
        // Reset and ignore
        _lastAppCopiedText = null;
        return;
      }

      // Use a post frame callback or ensure context is valid
      if (_context!.mounted) {
         _context!.read<ClipboardBloc>().add(AddClipboardItem(text));
         
         ScaffoldMessenger.of(_context!).showSnackBar(
          const SnackBar(
            content: Text('New clip detected!'),
            duration: Duration(seconds: 1),
          ),
        );
      }
    }
  }
}
